// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYj5ss4guP2_8z88fDrMhN6RBuRi5gqFI',
    appId: '1:1045540072681:web:13fe84fd0c4207609fd478',
    messagingSenderId: '1045540072681',
    projectId: 'miage-dev-mobile',
    authDomain: 'miage-dev-mobile.firebaseapp.com',
    storageBucket: 'miage-dev-mobile.appspot.com',
    measurementId: 'G-YVHV44P84Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN2x8_l_ZMS1k7kxKAI7LwBq7yo6a9qDQ',
    appId: '1:1045540072681:android:dff2cf2834656f429fd478',
    messagingSenderId: '1045540072681',
    projectId: 'miage-dev-mobile',
    storageBucket: 'miage-dev-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5VkoSZrVvkPYl5ztkXNv5NzL9F6sBcMY',
    appId: '1:1045540072681:ios:9cd0ecea232e65589fd478',
    messagingSenderId: '1045540072681',
    projectId: 'miage-dev-mobile',
    storageBucket: 'miage-dev-mobile.appspot.com',
    iosClientId: '1045540072681-and6mdokohtmgird6oir1lkc3q5qd1vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.devmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5VkoSZrVvkPYl5ztkXNv5NzL9F6sBcMY',
    appId: '1:1045540072681:ios:9cd0ecea232e65589fd478',
    messagingSenderId: '1045540072681',
    projectId: 'miage-dev-mobile',
    storageBucket: 'miage-dev-mobile.appspot.com',
    iosClientId: '1045540072681-and6mdokohtmgird6oir1lkc3q5qd1vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.devmobile',
  );
}
